// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TreeCraftingVoyager.Server.Data;

#nullable disable

namespace TreeCraftingVoyager.Server.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240413115625_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TreeCraftingVoyager.Server.Models.Entities.Category", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Description = "",
                            DisplayOrder = 0,
                            ImageURL = "",
                            Name = "Elektronika"
                        },
                        new
                        {
                            Id = 2L,
                            Description = "",
                            DisplayOrder = 0,
                            ImageURL = "",
                            Name = "Dom i ogród"
                        },
                        new
                        {
                            Id = 3L,
                            Description = "",
                            DisplayOrder = 0,
                            ImageURL = "",
                            Name = "Super market"
                        },
                        new
                        {
                            Id = 4L,
                            Description = "",
                            DisplayOrder = 0,
                            ImageURL = "",
                            Name = "Uroda"
                        },
                        new
                        {
                            Id = 5L,
                            Description = "",
                            DisplayOrder = 0,
                            ImageURL = "",
                            Name = "Zdrowie"
                        },
                        new
                        {
                            Id = 6L,
                            Description = "",
                            DisplayOrder = 0,
                            ImageURL = "",
                            Name = "Motoryzacja"
                        },
                        new
                        {
                            Id = 7L,
                            Description = "",
                            DisplayOrder = 0,
                            ImageURL = "",
                            Name = "Telefony i akcesoria",
                            ParentId = 1L
                        },
                        new
                        {
                            Id = 8L,
                            Description = "",
                            DisplayOrder = 0,
                            ImageURL = "",
                            Name = "Komputery",
                            ParentId = 1L
                        },
                        new
                        {
                            Id = 9L,
                            Description = "",
                            DisplayOrder = 0,
                            ImageURL = "",
                            Name = "AGD",
                            ParentId = 1L
                        },
                        new
                        {
                            Id = 10L,
                            Description = "",
                            DisplayOrder = 0,
                            ImageURL = "",
                            Name = "Wyposażenie",
                            ParentId = 2L
                        },
                        new
                        {
                            Id = 11L,
                            Description = "",
                            DisplayOrder = 0,
                            ImageURL = "",
                            Name = "Narzędzia",
                            ParentId = 2L
                        },
                        new
                        {
                            Id = 12L,
                            Description = "",
                            DisplayOrder = 0,
                            ImageURL = "",
                            Name = "Ogród",
                            ParentId = 2L
                        },
                        new
                        {
                            Id = 13L,
                            Description = "",
                            DisplayOrder = 0,
                            ImageURL = "",
                            Name = "Produkty spożywcze",
                            ParentId = 3L
                        },
                        new
                        {
                            Id = 14L,
                            Description = "",
                            DisplayOrder = 0,
                            ImageURL = "",
                            Name = "Artykuły dla zwierząt",
                            ParentId = 3L
                        },
                        new
                        {
                            Id = 15L,
                            Description = "",
                            DisplayOrder = 0,
                            ImageURL = "",
                            Name = "Utrzymanie czystości",
                            ParentId = 3L
                        },
                        new
                        {
                            Id = 16L,
                            Description = "",
                            DisplayOrder = 0,
                            ImageURL = "",
                            Name = "Pielęgnacja",
                            ParentId = 4L
                        },
                        new
                        {
                            Id = 17L,
                            Description = "",
                            DisplayOrder = 0,
                            ImageURL = "",
                            Name = "Makijaż",
                            ParentId = 4L
                        },
                        new
                        {
                            Id = 18L,
                            Description = "",
                            DisplayOrder = 0,
                            ImageURL = "",
                            Name = "Perfumy",
                            ParentId = 4L
                        },
                        new
                        {
                            Id = 19L,
                            Description = "",
                            DisplayOrder = 0,
                            ImageURL = "",
                            Name = "Domowa apteczka",
                            ParentId = 5L
                        },
                        new
                        {
                            Id = 20L,
                            Description = "",
                            DisplayOrder = 0,
                            ImageURL = "",
                            Name = "Urządzenia medyczne",
                            ParentId = 5L
                        },
                        new
                        {
                            Id = 21L,
                            Description = "",
                            DisplayOrder = 0,
                            ImageURL = "",
                            Name = "Medycyna naturalna",
                            ParentId = 5L
                        },
                        new
                        {
                            Id = 22L,
                            Description = "",
                            DisplayOrder = 0,
                            ImageURL = "",
                            Name = "Opony i felgi",
                            ParentId = 6L
                        },
                        new
                        {
                            Id = 23L,
                            Description = "",
                            DisplayOrder = 0,
                            ImageURL = "",
                            Name = "Części samochodowe",
                            ParentId = 6L
                        },
                        new
                        {
                            Id = 24L,
                            Description = "",
                            DisplayOrder = 0,
                            ImageURL = "",
                            Name = "Warsztat",
                            ParentId = 6L
                        },
                        new
                        {
                            Id = 25L,
                            Description = "",
                            DisplayOrder = 0,
                            ImageURL = "",
                            Name = "Smartfony",
                            ParentId = 7L
                        },
                        new
                        {
                            Id = 26L,
                            Description = "",
                            DisplayOrder = 0,
                            ImageURL = "",
                            Name = "Tablety",
                            ParentId = 7L
                        },
                        new
                        {
                            Id = 27L,
                            Description = "",
                            DisplayOrder = 0,
                            ImageURL = "",
                            Name = "Laptopy",
                            ParentId = 8L
                        },
                        new
                        {
                            Id = 28L,
                            Description = "",
                            DisplayOrder = 0,
                            ImageURL = "",
                            Name = "Komputery stacjonarne",
                            ParentId = 8L
                        },
                        new
                        {
                            Id = 29L,
                            Description = "",
                            DisplayOrder = 0,
                            ImageURL = "",
                            Name = "AGD małe",
                            ParentId = 9L
                        },
                        new
                        {
                            Id = 30L,
                            Description = "",
                            DisplayOrder = 0,
                            ImageURL = "",
                            Name = "AGD do zabudowy",
                            ParentId = 9L
                        },
                        new
                        {
                            Id = 31L,
                            Description = "",
                            DisplayOrder = 0,
                            ImageURL = "",
                            Name = "AGD",
                            ParentId = 9L
                        },
                        new
                        {
                            Id = 32L,
                            Description = "",
                            DisplayOrder = 0,
                            ImageURL = "",
                            Name = "Garnki i patelnie",
                            ParentId = 10L
                        },
                        new
                        {
                            Id = 33L,
                            Description = "",
                            DisplayOrder = 0,
                            ImageURL = "",
                            Name = "Dekoracje i ozdoby",
                            ParentId = 10L
                        },
                        new
                        {
                            Id = 34L,
                            Description = "",
                            DisplayOrder = 0,
                            ImageURL = "",
                            Name = "Piły i pilarki",
                            ParentId = 11L
                        },
                        new
                        {
                            Id = 35L,
                            Description = "",
                            DisplayOrder = 0,
                            ImageURL = "",
                            Name = "Odkurzacze przemysłowe",
                            ParentId = 11L
                        },
                        new
                        {
                            Id = 36L,
                            Description = "",
                            DisplayOrder = 0,
                            ImageURL = "",
                            Name = "Nawozy i preparaty",
                            ParentId = 12L
                        },
                        new
                        {
                            Id = 37L,
                            Description = "",
                            DisplayOrder = 0,
                            ImageURL = "",
                            Name = "Meble ogrodowe",
                            ParentId = 12L
                        },
                        new
                        {
                            Id = 38L,
                            Description = "",
                            DisplayOrder = 0,
                            ImageURL = "",
                            Name = "Kawy",
                            ParentId = 13L
                        },
                        new
                        {
                            Id = 39L,
                            Description = "",
                            DisplayOrder = 0,
                            ImageURL = "",
                            Name = "Herbaty",
                            ParentId = 13L
                        },
                        new
                        {
                            Id = 40L,
                            Description = "",
                            DisplayOrder = 0,
                            ImageURL = "",
                            Name = "Karmy",
                            ParentId = 14L
                        },
                        new
                        {
                            Id = 41L,
                            Description = "",
                            DisplayOrder = 0,
                            ImageURL = "",
                            Name = "Legowiska",
                            ParentId = 14L
                        },
                        new
                        {
                            Id = 42L,
                            Description = "",
                            DisplayOrder = 0,
                            ImageURL = "",
                            Name = "Środki czyszczące",
                            ParentId = 15L
                        },
                        new
                        {
                            Id = 43L,
                            Description = "",
                            DisplayOrder = 0,
                            ImageURL = "",
                            Name = "Suszarki na pranie",
                            ParentId = 15L
                        },
                        new
                        {
                            Id = 44L,
                            Description = "",
                            DisplayOrder = 0,
                            ImageURL = "",
                            Name = "Kremy do twarzy",
                            ParentId = 16L
                        },
                        new
                        {
                            Id = 45L,
                            Description = "",
                            DisplayOrder = 0,
                            ImageURL = "",
                            Name = "Szampony",
                            ParentId = 16L
                        },
                        new
                        {
                            Id = 46L,
                            Description = "",
                            DisplayOrder = 0,
                            ImageURL = "",
                            Name = "Makijaż ust",
                            ParentId = 17L
                        },
                        new
                        {
                            Id = 47L,
                            Description = "",
                            DisplayOrder = 0,
                            ImageURL = "",
                            Name = "Sztuczne rzęsy",
                            ParentId = 17L
                        },
                        new
                        {
                            Id = 48L,
                            Description = "",
                            DisplayOrder = 0,
                            ImageURL = "",
                            Name = "Zestawy",
                            ParentId = 18L
                        },
                        new
                        {
                            Id = 49L,
                            Description = "",
                            DisplayOrder = 0,
                            ImageURL = "",
                            Name = "Wody toaletowe",
                            ParentId = 18L
                        },
                        new
                        {
                            Id = 50L,
                            Description = "",
                            DisplayOrder = 0,
                            ImageURL = "",
                            Name = "Suplementy diety",
                            ParentId = 19L
                        },
                        new
                        {
                            Id = 51L,
                            Description = "",
                            DisplayOrder = 0,
                            ImageURL = "",
                            Name = "Leki bez recepty",
                            ParentId = 19L
                        },
                        new
                        {
                            Id = 52L,
                            Description = "",
                            DisplayOrder = 0,
                            ImageURL = "",
                            Name = "Inhalatory",
                            ParentId = 20L
                        },
                        new
                        {
                            Id = 53L,
                            Description = "",
                            DisplayOrder = 0,
                            ImageURL = "",
                            Name = "Termometry",
                            ParentId = 20L
                        },
                        new
                        {
                            Id = 54L,
                            Description = "",
                            DisplayOrder = 0,
                            ImageURL = "",
                            Name = "Produkty konopne",
                            ParentId = 21L
                        },
                        new
                        {
                            Id = 55L,
                            Description = "",
                            DisplayOrder = 0,
                            ImageURL = "",
                            Name = "Olejki eteryczne",
                            ParentId = 21L
                        },
                        new
                        {
                            Id = 56L,
                            Description = "",
                            DisplayOrder = 0,
                            ImageURL = "",
                            Name = "Felgi aluminiowe",
                            ParentId = 22L
                        },
                        new
                        {
                            Id = 57L,
                            Description = "",
                            DisplayOrder = 0,
                            ImageURL = "",
                            Name = "Do motocykli",
                            ParentId = 22L
                        },
                        new
                        {
                            Id = 58L,
                            Description = "",
                            DisplayOrder = 0,
                            ImageURL = "",
                            Name = "Układ zawieszenia",
                            ParentId = 23L
                        },
                        new
                        {
                            Id = 59L,
                            Description = "",
                            DisplayOrder = 0,
                            ImageURL = "",
                            Name = "Części karoserii",
                            ParentId = 23L
                        },
                        new
                        {
                            Id = 60L,
                            Description = "",
                            DisplayOrder = 0,
                            ImageURL = "",
                            Name = "Zestawy narzędzi",
                            ParentId = 24L
                        },
                        new
                        {
                            Id = 61L,
                            Description = "",
                            DisplayOrder = 0,
                            ImageURL = "",
                            Name = "Klucze",
                            ParentId = 24L
                        },
                        new
                        {
                            Id = 62L,
                            Description = "",
                            DisplayOrder = 0,
                            ImageURL = "",
                            Name = "Odkurzacze pionowe",
                            ParentId = 29L
                        },
                        new
                        {
                            Id = 63L,
                            Description = "",
                            DisplayOrder = 0,
                            ImageURL = "",
                            Name = "Do kuchni",
                            ParentId = 29L
                        },
                        new
                        {
                            Id = 64L,
                            Description = "",
                            DisplayOrder = 0,
                            ImageURL = "",
                            Name = "Płyty grzewcze",
                            ParentId = 30L
                        },
                        new
                        {
                            Id = 65L,
                            Description = "",
                            DisplayOrder = 0,
                            ImageURL = "",
                            Name = "Okapy",
                            ParentId = 30L
                        },
                        new
                        {
                            Id = 66L,
                            Description = "",
                            DisplayOrder = 0,
                            ImageURL = "",
                            Name = "Lodówki",
                            ParentId = 31L
                        },
                        new
                        {
                            Id = 67L,
                            Description = "",
                            DisplayOrder = 0,
                            ImageURL = "",
                            Name = "Pralki",
                            ParentId = 31L
                        });
                });

            modelBuilder.Entity("TreeCraftingVoyager.Server.Models.Entities.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CategoryId = 1L,
                            Description = "Jakiś tam produkt elektroniczny",
                            ExpirationDate = new DateTime(2027, 1, 8, 11, 56, 24, 63, DateTimeKind.Utc).AddTicks(3456),
                            Name = "Coś elektronicznego",
                            Price = 1.2m
                        },
                        new
                        {
                            Id = 2L,
                            CategoryId = 2L,
                            Description = "Jakiś tam produkt do domu i ogrodu",
                            ExpirationDate = new DateTime(2024, 7, 22, 11, 56, 24, 63, DateTimeKind.Utc).AddTicks(4549),
                            Name = "Coś do domu i ogrodu",
                            Price = 20.3m
                        },
                        new
                        {
                            Id = 3L,
                            CategoryId = 3L,
                            Description = "Jakiś tam produkt z super marketu",
                            ExpirationDate = new DateTime(2024, 4, 15, 11, 56, 24, 63, DateTimeKind.Utc).AddTicks(4554),
                            Name = "Coś z super marketu",
                            Price = 2.2m
                        },
                        new
                        {
                            Id = 4L,
                            CategoryId = 4L,
                            Description = "Jakiś tam produkt dla urody",
                            ExpirationDate = new DateTime(2024, 5, 8, 11, 56, 24, 63, DateTimeKind.Utc).AddTicks(4583),
                            Name = "Coś dla urody",
                            Price = 30.2m
                        },
                        new
                        {
                            Id = 5L,
                            CategoryId = 5L,
                            Description = "Jakiś tam produkt dla zdrowia",
                            ExpirationDate = new DateTime(2024, 5, 13, 11, 56, 24, 63, DateTimeKind.Utc).AddTicks(4592),
                            Name = "Coś dla zdrowia",
                            Price = 11.2m
                        },
                        new
                        {
                            Id = 6L,
                            CategoryId = 6L,
                            Description = "Jakiś tam produkt dla motoryzacji",
                            ExpirationDate = new DateTime(2025, 2, 7, 11, 56, 24, 63, DateTimeKind.Utc).AddTicks(4608),
                            Name = "Coś dla motoryzacji",
                            Price = 1123.2m
                        },
                        new
                        {
                            Id = 7L,
                            CategoryId = 7L,
                            Description = "Telefony i akcesoria",
                            ExpirationDate = new DateTime(2024, 5, 6, 11, 56, 24, 63, DateTimeKind.Utc).AddTicks(4614),
                            Name = "Jakiś tam telefon",
                            Price = 1.2m
                        },
                        new
                        {
                            Id = 8L,
                            CategoryId = 8L,
                            Description = "Komputery",
                            ExpirationDate = new DateTime(2024, 5, 17, 11, 56, 24, 63, DateTimeKind.Utc).AddTicks(4617),
                            Name = "Jakiś tam komputer",
                            Price = 112.2m
                        },
                        new
                        {
                            Id = 9L,
                            CategoryId = 9L,
                            Description = "AGD",
                            ExpirationDate = new DateTime(2024, 6, 8, 11, 56, 24, 63, DateTimeKind.Utc).AddTicks(4619),
                            Name = "Jakaś tam lodówka",
                            Price = 112.26m
                        },
                        new
                        {
                            Id = 10L,
                            CategoryId = 10L,
                            Description = "Wyposażenie",
                            ExpirationDate = new DateTime(2025, 4, 8, 11, 56, 24, 63, DateTimeKind.Utc).AddTicks(4751),
                            Name = "Jakiś tam obraz",
                            Price = 112.22m
                        },
                        new
                        {
                            Id = 11L,
                            CategoryId = 11L,
                            Description = "Narzędzia",
                            ExpirationDate = new DateTime(2024, 5, 27, 11, 56, 24, 63, DateTimeKind.Utc).AddTicks(4756),
                            Name = "Jakiś tam młotek",
                            Price = 112.24m
                        },
                        new
                        {
                            Id = 12L,
                            CategoryId = 12L,
                            Description = "Ogród",
                            ExpirationDate = new DateTime(2033, 9, 23, 11, 56, 24, 63, DateTimeKind.Utc).AddTicks(4758),
                            Name = "Jakaś tam doniczka",
                            Price = 1212.2m
                        },
                        new
                        {
                            Id = 13L,
                            CategoryId = 13L,
                            Description = "Produkty spożywcze",
                            ExpirationDate = new DateTime(2024, 4, 24, 11, 56, 24, 63, DateTimeKind.Utc).AddTicks(4761),
                            Name = "Jakiś tam chleb",
                            Price = 1412.2m
                        },
                        new
                        {
                            Id = 14L,
                            CategoryId = 14L,
                            Description = "Artykuły dla zwierząt",
                            ExpirationDate = new DateTime(2024, 4, 14, 11, 56, 24, 63, DateTimeKind.Utc).AddTicks(4768),
                            Name = "Jakaś tam karma ogólna",
                            Price = 112.2m
                        },
                        new
                        {
                            Id = 15L,
                            CategoryId = 15L,
                            Description = "Utrzymanie czystości",
                            ExpirationDate = new DateTime(2024, 5, 6, 11, 56, 24, 63, DateTimeKind.Utc).AddTicks(4794),
                            Name = "Jakaś tam miotła",
                            Price = 234m
                        },
                        new
                        {
                            Id = 16L,
                            CategoryId = 16L,
                            Description = "Pielęgnacja",
                            ExpirationDate = new DateTime(2024, 4, 24, 11, 56, 24, 63, DateTimeKind.Utc).AddTicks(4800),
                            Name = "Jakiś tam krem",
                            Price = 1412.2m
                        },
                        new
                        {
                            Id = 17L,
                            CategoryId = 17L,
                            Description = "Makijaż",
                            ExpirationDate = new DateTime(2024, 4, 14, 11, 56, 24, 63, DateTimeKind.Utc).AddTicks(4803),
                            Name = "Jakaś tam podkład",
                            Price = 112.2m
                        },
                        new
                        {
                            Id = 18L,
                            CategoryId = 18L,
                            Description = "Perfumy",
                            ExpirationDate = new DateTime(2024, 5, 6, 11, 56, 24, 63, DateTimeKind.Utc).AddTicks(4811),
                            Name = "Jakaś tam dezodorant",
                            Price = 234m
                        },
                        new
                        {
                            Id = 19L,
                            CategoryId = 19L,
                            Description = "Domowa apteczka",
                            ExpirationDate = new DateTime(2024, 4, 24, 11, 56, 24, 63, DateTimeKind.Utc).AddTicks(4816),
                            Name = "Jakiś tam bandarz",
                            Price = 1412.2m
                        },
                        new
                        {
                            Id = 20L,
                            CategoryId = 20L,
                            Description = "Urządzenia medyczne",
                            ExpirationDate = new DateTime(2024, 4, 14, 11, 56, 24, 63, DateTimeKind.Utc).AddTicks(4818),
                            Name = "Jakiś tam rozrusznik serca",
                            Price = 112.2m
                        },
                        new
                        {
                            Id = 21L,
                            CategoryId = 21L,
                            Description = "Medycyna naturalna",
                            ExpirationDate = new DateTime(2024, 5, 6, 11, 56, 24, 63, DateTimeKind.Utc).AddTicks(4821),
                            Name = "Jakaś tam herbatka naturalna",
                            Price = 234m
                        },
                        new
                        {
                            Id = 22L,
                            CategoryId = 22L,
                            Description = "Opony i felgi",
                            ExpirationDate = new DateTime(2024, 8, 22, 11, 56, 24, 63, DateTimeKind.Utc).AddTicks(4823),
                            Name = "Jakieś tam felgi",
                            Price = 1412.2m
                        },
                        new
                        {
                            Id = 23L,
                            CategoryId = 23L,
                            Description = "Części samochodowe",
                            ExpirationDate = new DateTime(2024, 8, 14, 11, 56, 24, 63, DateTimeKind.Utc).AddTicks(4825),
                            Name = "Jakaś tam lampa",
                            Price = 112.2m
                        },
                        new
                        {
                            Id = 24L,
                            CategoryId = 24L,
                            Description = "Warsztat",
                            ExpirationDate = new DateTime(2024, 4, 24, 11, 56, 24, 63, DateTimeKind.Utc).AddTicks(4827),
                            Name = "Jakaś tam śrubka",
                            Price = 234m
                        },
                        new
                        {
                            Id = 25L,
                            CategoryId = 25L,
                            Description = "",
                            ExpirationDate = new DateTime(2024, 8, 14, 11, 56, 24, 63, DateTimeKind.Utc).AddTicks(4830),
                            Name = "Jakaś tam ",
                            Price = 112.2m
                        },
                        new
                        {
                            Id = 26L,
                            CategoryId = 26L,
                            Description = "",
                            ExpirationDate = new DateTime(2024, 4, 24, 11, 56, 24, 63, DateTimeKind.Utc).AddTicks(4906),
                            Name = "Jakaś tam ",
                            Price = 234.1m
                        });
                });

            modelBuilder.Entity("TreeCraftingVoyager.Server.Models.Entities.Category", b =>
                {
                    b.HasOne("TreeCraftingVoyager.Server.Models.Entities.Category", "Parent")
                        .WithMany("Childrens")
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("TreeCraftingVoyager.Server.Models.Entities.Product", b =>
                {
                    b.HasOne("TreeCraftingVoyager.Server.Models.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("TreeCraftingVoyager.Server.Models.Entities.Category", b =>
                {
                    b.Navigation("Childrens");
                });
#pragma warning restore 612, 618
        }
    }
}
