// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TreeCraftingVoyager.Server.Data;

#nullable disable

namespace TreeCraftingVoyager.Server.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TreeCraftingVoyager.Server.Models.Entities.Category", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Description = "root",
                            DisplayOrder = 3,
                            ImageURL = "https://www.examplesite.pl",
                            Name = "Elektronika"
                        },
                        new
                        {
                            Id = 2L,
                            Description = "root",
                            DisplayOrder = 4,
                            ImageURL = "https://www.examplesite.pl",
                            Name = "Dom i ogród"
                        },
                        new
                        {
                            Id = 3L,
                            Description = "root",
                            DisplayOrder = 2,
                            ImageURL = "https://www.examplesite.pl",
                            Name = "Super market"
                        },
                        new
                        {
                            Id = 4L,
                            Description = "root",
                            DisplayOrder = 5,
                            ImageURL = "https://www.examplesite.pl",
                            Name = "Uroda"
                        },
                        new
                        {
                            Id = 5L,
                            Description = "root",
                            DisplayOrder = 6,
                            ImageURL = "https://www.examplesite.pl",
                            Name = "Zdrowie"
                        },
                        new
                        {
                            Id = 6L,
                            Description = "root",
                            DisplayOrder = 1,
                            ImageURL = "https://www.examplesite.pl",
                            Name = "Motoryzacja"
                        },
                        new
                        {
                            Id = 7L,
                            Description = "first child",
                            DisplayOrder = 2,
                            ImageURL = "https://www.examplesite.pl",
                            Name = "Telefony i akcesoria",
                            ParentId = 1L
                        },
                        new
                        {
                            Id = 8L,
                            Description = "first child",
                            DisplayOrder = 1,
                            ImageURL = "https://www.examplesite.pl",
                            Name = "Komputery",
                            ParentId = 1L
                        },
                        new
                        {
                            Id = 9L,
                            Description = "first child",
                            DisplayOrder = 3,
                            ImageURL = "https://www.examplesite.pl",
                            Name = "AGD",
                            ParentId = 1L
                        },
                        new
                        {
                            Id = 10L,
                            Description = "first child",
                            DisplayOrder = 2,
                            ImageURL = "https://www.examplesite.pl",
                            Name = "Wyposażenie",
                            ParentId = 2L
                        },
                        new
                        {
                            Id = 11L,
                            Description = "first child",
                            DisplayOrder = 1,
                            ImageURL = "https://www.examplesite.pl",
                            Name = "Narzędzia",
                            ParentId = 2L
                        },
                        new
                        {
                            Id = 12L,
                            Description = "first child",
                            DisplayOrder = 3,
                            ImageURL = "https://www.examplesite.pl",
                            Name = "Ogród",
                            ParentId = 2L
                        },
                        new
                        {
                            Id = 13L,
                            Description = "first child",
                            DisplayOrder = 1,
                            ImageURL = "https://www.examplesite.pl",
                            Name = "Produkty spożywcze",
                            ParentId = 3L
                        },
                        new
                        {
                            Id = 14L,
                            Description = "first child",
                            DisplayOrder = 2,
                            ImageURL = "https://www.examplesite.pl",
                            Name = "Artykuły dla zwierząt",
                            ParentId = 3L
                        },
                        new
                        {
                            Id = 15L,
                            Description = "first child",
                            DisplayOrder = 3,
                            ImageURL = "https://www.examplesite.pl",
                            Name = "Utrzymanie czystości",
                            ParentId = 3L
                        },
                        new
                        {
                            Id = 16L,
                            Description = "first child",
                            DisplayOrder = 2,
                            ImageURL = "https://www.examplesite.pl",
                            Name = "Pielęgnacja",
                            ParentId = 4L
                        },
                        new
                        {
                            Id = 17L,
                            Description = "first child",
                            DisplayOrder = 3,
                            ImageURL = "https://www.examplesite.pl",
                            Name = "Makijaż",
                            ParentId = 4L
                        },
                        new
                        {
                            Id = 18L,
                            Description = "first child",
                            DisplayOrder = 1,
                            ImageURL = "https://www.examplesite.pl",
                            Name = "Perfumy",
                            ParentId = 4L
                        },
                        new
                        {
                            Id = 19L,
                            Description = "first child",
                            DisplayOrder = 2,
                            ImageURL = "https://www.examplesite.pl",
                            Name = "Domowa apteczka",
                            ParentId = 5L
                        },
                        new
                        {
                            Id = 20L,
                            Description = "first child",
                            DisplayOrder = 3,
                            ImageURL = "https://www.examplesite.pl",
                            Name = "Urządzenia medyczne",
                            ParentId = 5L
                        },
                        new
                        {
                            Id = 21L,
                            Description = "first child",
                            DisplayOrder = 1,
                            ImageURL = "https://www.examplesite.pl",
                            Name = "Medycyna naturalna",
                            ParentId = 5L
                        },
                        new
                        {
                            Id = 22L,
                            Description = "first child",
                            DisplayOrder = 1,
                            ImageURL = "https://www.examplesite.pl",
                            Name = "Opony i felgi",
                            ParentId = 6L
                        },
                        new
                        {
                            Id = 23L,
                            Description = "first child",
                            DisplayOrder = 2,
                            ImageURL = "https://www.examplesite.pl",
                            Name = "Części samochodowe",
                            ParentId = 6L
                        },
                        new
                        {
                            Id = 24L,
                            Description = "first child",
                            DisplayOrder = 3,
                            ImageURL = "https://www.examplesite.pl",
                            Name = "Warsztat",
                            ParentId = 6L
                        },
                        new
                        {
                            Id = 25L,
                            Description = "second child",
                            DisplayOrder = 1,
                            ImageURL = "https://www.examplesite.pl",
                            Name = "Smartfony",
                            ParentId = 7L
                        },
                        new
                        {
                            Id = 26L,
                            Description = "second child",
                            DisplayOrder = 2,
                            ImageURL = "https://www.examplesite.pl",
                            Name = "Tablety",
                            ParentId = 7L
                        },
                        new
                        {
                            Id = 27L,
                            Description = "second child",
                            DisplayOrder = 2,
                            ImageURL = "https://www.examplesite.pl",
                            Name = "Laptopy",
                            ParentId = 8L
                        },
                        new
                        {
                            Id = 28L,
                            Description = "second child",
                            DisplayOrder = 1,
                            ImageURL = "https://www.examplesite.pl",
                            Name = "Komputery stacjonarne",
                            ParentId = 8L
                        },
                        new
                        {
                            Id = 29L,
                            Description = "second child",
                            DisplayOrder = 3,
                            ImageURL = "https://www.examplesite.pl",
                            Name = "AGD małe",
                            ParentId = 9L
                        },
                        new
                        {
                            Id = 30L,
                            Description = "second child",
                            DisplayOrder = 2,
                            ImageURL = "https://www.examplesite.pl",
                            Name = "AGD do zabudowy",
                            ParentId = 9L
                        },
                        new
                        {
                            Id = 31L,
                            Description = "second child",
                            DisplayOrder = 1,
                            ImageURL = "https://www.examplesite.pl",
                            Name = "AGD",
                            ParentId = 9L
                        },
                        new
                        {
                            Id = 32L,
                            Description = "second child",
                            DisplayOrder = 1,
                            ImageURL = "https://www.examplesite.pl",
                            Name = "Garnki i patelnie",
                            ParentId = 10L
                        },
                        new
                        {
                            Id = 33L,
                            Description = "second child",
                            DisplayOrder = 2,
                            ImageURL = "https://www.examplesite.pl",
                            Name = "Dekoracje i ozdoby",
                            ParentId = 10L
                        },
                        new
                        {
                            Id = 34L,
                            Description = "second child",
                            DisplayOrder = 1,
                            ImageURL = "https://www.examplesite.pl",
                            Name = "Piły i pilarki",
                            ParentId = 11L
                        },
                        new
                        {
                            Id = 35L,
                            Description = "second child",
                            DisplayOrder = 2,
                            ImageURL = "https://www.examplesite.pl",
                            Name = "Odkurzacze przemysłowe",
                            ParentId = 11L
                        },
                        new
                        {
                            Id = 36L,
                            Description = "second child",
                            DisplayOrder = 1,
                            ImageURL = "https://www.examplesite.pl",
                            Name = "Nawozy i preparaty",
                            ParentId = 12L
                        },
                        new
                        {
                            Id = 37L,
                            Description = "second child",
                            DisplayOrder = 2,
                            ImageURL = "https://www.examplesite.pl",
                            Name = "Meble ogrodowe",
                            ParentId = 12L
                        },
                        new
                        {
                            Id = 38L,
                            Description = "second child",
                            DisplayOrder = 2,
                            ImageURL = "https://www.examplesite.pl",
                            Name = "Kawy",
                            ParentId = 13L
                        },
                        new
                        {
                            Id = 39L,
                            Description = "second child",
                            DisplayOrder = 1,
                            ImageURL = "https://www.examplesite.pl",
                            Name = "Herbaty",
                            ParentId = 13L
                        },
                        new
                        {
                            Id = 40L,
                            Description = "second child",
                            DisplayOrder = 1,
                            ImageURL = "https://www.examplesite.pl",
                            Name = "Karmy",
                            ParentId = 14L
                        },
                        new
                        {
                            Id = 41L,
                            Description = "second child",
                            DisplayOrder = 2,
                            ImageURL = "https://www.examplesite.pl",
                            Name = "Legowiska",
                            ParentId = 14L
                        },
                        new
                        {
                            Id = 42L,
                            Description = "second child",
                            DisplayOrder = 2,
                            ImageURL = "https://www.examplesite.pl",
                            Name = "Środki czyszczące",
                            ParentId = 15L
                        },
                        new
                        {
                            Id = 43L,
                            Description = "second child",
                            DisplayOrder = 1,
                            ImageURL = "https://www.examplesite.pl",
                            Name = "Suszarki na pranie",
                            ParentId = 15L
                        },
                        new
                        {
                            Id = 44L,
                            Description = "second child",
                            DisplayOrder = 2,
                            ImageURL = "https://www.examplesite.pl",
                            Name = "Kremy do twarzy",
                            ParentId = 16L
                        },
                        new
                        {
                            Id = 45L,
                            Description = "second child",
                            DisplayOrder = 1,
                            ImageURL = "https://www.examplesite.pl",
                            Name = "Szampony",
                            ParentId = 16L
                        },
                        new
                        {
                            Id = 46L,
                            Description = "second child",
                            DisplayOrder = 1,
                            ImageURL = "https://www.examplesite.pl",
                            Name = "Makijaż ust",
                            ParentId = 17L
                        },
                        new
                        {
                            Id = 47L,
                            Description = "second child",
                            DisplayOrder = 2,
                            ImageURL = "https://www.examplesite.pl",
                            Name = "Sztuczne rzęsy",
                            ParentId = 17L
                        },
                        new
                        {
                            Id = 48L,
                            Description = "second child",
                            DisplayOrder = 2,
                            ImageURL = "https://www.examplesite.pl",
                            Name = "Zestawy",
                            ParentId = 18L
                        },
                        new
                        {
                            Id = 49L,
                            Description = "second child",
                            DisplayOrder = 1,
                            ImageURL = "https://www.examplesite.pl",
                            Name = "Wody toaletowe",
                            ParentId = 18L
                        },
                        new
                        {
                            Id = 50L,
                            Description = "second child",
                            DisplayOrder = 1,
                            ImageURL = "https://www.examplesite.pl",
                            Name = "Suplementy diety",
                            ParentId = 19L
                        },
                        new
                        {
                            Id = 51L,
                            Description = "second child",
                            DisplayOrder = 2,
                            ImageURL = "https://www.examplesite.pl",
                            Name = "Leki bez recepty",
                            ParentId = 19L
                        },
                        new
                        {
                            Id = 52L,
                            Description = "second child",
                            DisplayOrder = 2,
                            ImageURL = "https://www.examplesite.pl",
                            Name = "Inhalatory",
                            ParentId = 20L
                        },
                        new
                        {
                            Id = 53L,
                            Description = "second child",
                            DisplayOrder = 1,
                            ImageURL = "https://www.examplesite.pl",
                            Name = "Termometry",
                            ParentId = 20L
                        },
                        new
                        {
                            Id = 54L,
                            Description = "second child",
                            DisplayOrder = 1,
                            ImageURL = "https://www.examplesite.pl",
                            Name = "Produkty konopne",
                            ParentId = 21L
                        },
                        new
                        {
                            Id = 55L,
                            Description = "second child",
                            DisplayOrder = 2,
                            ImageURL = "https://www.examplesite.pl",
                            Name = "Olejki eteryczne",
                            ParentId = 21L
                        },
                        new
                        {
                            Id = 56L,
                            Description = "second child",
                            DisplayOrder = 1,
                            ImageURL = "https://www.examplesite.pl",
                            Name = "Felgi aluminiowe",
                            ParentId = 22L
                        },
                        new
                        {
                            Id = 57L,
                            Description = "second child",
                            DisplayOrder = 2,
                            ImageURL = "https://www.examplesite.pl",
                            Name = "Do motocykli",
                            ParentId = 22L
                        },
                        new
                        {
                            Id = 58L,
                            Description = "second child",
                            DisplayOrder = 2,
                            ImageURL = "https://www.examplesite.pl",
                            Name = "Układ zawieszenia",
                            ParentId = 23L
                        },
                        new
                        {
                            Id = 59L,
                            Description = "second child",
                            DisplayOrder = 1,
                            ImageURL = "https://www.examplesite.pl",
                            Name = "Części karoserii",
                            ParentId = 23L
                        },
                        new
                        {
                            Id = 60L,
                            Description = "second child",
                            DisplayOrder = 2,
                            ImageURL = "https://www.examplesite.pl",
                            Name = "Zestawy narzędzi",
                            ParentId = 24L
                        },
                        new
                        {
                            Id = 61L,
                            Description = "second child",
                            DisplayOrder = 1,
                            ImageURL = "https://www.examplesite.pl",
                            Name = "Klucze",
                            ParentId = 24L
                        },
                        new
                        {
                            Id = 62L,
                            Description = "third child",
                            DisplayOrder = 1,
                            ImageURL = "https://www.examplesite.pl",
                            Name = "Odkurzacze pionowe",
                            ParentId = 29L
                        },
                        new
                        {
                            Id = 63L,
                            Description = "third child",
                            DisplayOrder = 2,
                            ImageURL = "https://www.examplesite.pl",
                            Name = "Do kuchni",
                            ParentId = 29L
                        },
                        new
                        {
                            Id = 64L,
                            Description = "third child",
                            DisplayOrder = 2,
                            ImageURL = "https://www.examplesite.pl",
                            Name = "Płyty grzewcze",
                            ParentId = 30L
                        },
                        new
                        {
                            Id = 65L,
                            Description = "third child",
                            DisplayOrder = 1,
                            ImageURL = "https://www.examplesite.pl",
                            Name = "Okapy",
                            ParentId = 30L
                        },
                        new
                        {
                            Id = 66L,
                            Description = "third child",
                            DisplayOrder = 1,
                            ImageURL = "https://www.examplesite.pl",
                            Name = "Lodówki",
                            ParentId = 31L
                        },
                        new
                        {
                            Id = 67L,
                            Description = "third child",
                            DisplayOrder = 2,
                            ImageURL = "https://www.examplesite.pl",
                            Name = "Pralki",
                            ParentId = 31L
                        });
                });

            modelBuilder.Entity("TreeCraftingVoyager.Server.Models.Entities.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CategoryId = 1L,
                            Description = "Elektronika",
                            ExpirationDate = new DateTime(2027, 3, 15, 17, 17, 20, 537, DateTimeKind.Utc).AddTicks(6315),
                            Name = "Coś elektronicznego",
                            Price = 1.2m
                        },
                        new
                        {
                            Id = 2L,
                            CategoryId = 2L,
                            Description = "Dom i ogród",
                            ExpirationDate = new DateTime(2024, 9, 26, 17, 17, 20, 537, DateTimeKind.Utc).AddTicks(7298),
                            Name = "Coś do domu i ogrodu",
                            Price = 20.3m
                        },
                        new
                        {
                            Id = 3L,
                            CategoryId = 3L,
                            Description = "Super market",
                            ExpirationDate = new DateTime(2024, 6, 20, 17, 17, 20, 537, DateTimeKind.Utc).AddTicks(7302),
                            Name = "Coś z super marketu",
                            Price = 2.2m
                        },
                        new
                        {
                            Id = 4L,
                            CategoryId = 4L,
                            Description = "Uroda",
                            ExpirationDate = new DateTime(2024, 7, 13, 17, 17, 20, 537, DateTimeKind.Utc).AddTicks(7304),
                            Name = "Coś dla urody",
                            Price = 30.2m
                        },
                        new
                        {
                            Id = 5L,
                            CategoryId = 5L,
                            Description = "Zdrowie",
                            ExpirationDate = new DateTime(2024, 7, 18, 17, 17, 20, 537, DateTimeKind.Utc).AddTicks(7307),
                            Name = "Coś dla zdrowia",
                            Price = 11.2m
                        },
                        new
                        {
                            Id = 6L,
                            CategoryId = 6L,
                            Description = "Motoryzacja",
                            ExpirationDate = new DateTime(2025, 4, 14, 17, 17, 20, 537, DateTimeKind.Utc).AddTicks(7319),
                            Name = "Coś dla motoryzacji",
                            Price = 1123.2m
                        },
                        new
                        {
                            Id = 7L,
                            CategoryId = 7L,
                            Description = "Telefony i akcesoria",
                            ExpirationDate = new DateTime(2024, 7, 11, 17, 17, 20, 537, DateTimeKind.Utc).AddTicks(7345),
                            Name = "Jakiś tam telefon",
                            Price = 1.2m
                        },
                        new
                        {
                            Id = 8L,
                            CategoryId = 8L,
                            Description = "Komputery",
                            ExpirationDate = new DateTime(2024, 7, 22, 17, 17, 20, 537, DateTimeKind.Utc).AddTicks(7347),
                            Name = "Jakiś tam komputer",
                            Price = 112.2m
                        },
                        new
                        {
                            Id = 9L,
                            CategoryId = 9L,
                            Description = "AGD",
                            ExpirationDate = new DateTime(2024, 8, 13, 17, 17, 20, 537, DateTimeKind.Utc).AddTicks(7497),
                            Name = "Jakaś tam lodówka",
                            Price = 112.26m
                        },
                        new
                        {
                            Id = 10L,
                            CategoryId = 10L,
                            Description = "Wyposażenie",
                            ExpirationDate = new DateTime(2025, 6, 13, 17, 17, 20, 537, DateTimeKind.Utc).AddTicks(7504),
                            Name = "Jakiś tam obraz",
                            Price = 112.22m
                        },
                        new
                        {
                            Id = 11L,
                            CategoryId = 11L,
                            Description = "Narzędzia",
                            ExpirationDate = new DateTime(2024, 8, 1, 17, 17, 20, 537, DateTimeKind.Utc).AddTicks(7507),
                            Name = "Jakiś tam młotek",
                            Price = 112.24m
                        },
                        new
                        {
                            Id = 12L,
                            CategoryId = 12L,
                            Description = "Ogród",
                            ExpirationDate = new DateTime(2033, 11, 28, 17, 17, 20, 537, DateTimeKind.Utc).AddTicks(7509),
                            Name = "Jakaś tam doniczka",
                            Price = 1212.2m
                        },
                        new
                        {
                            Id = 13L,
                            CategoryId = 13L,
                            Description = "Produkty spożywcze",
                            ExpirationDate = new DateTime(2024, 6, 29, 17, 17, 20, 537, DateTimeKind.Utc).AddTicks(7511),
                            Name = "Jakiś tam chleb",
                            Price = 1412.2m
                        },
                        new
                        {
                            Id = 14L,
                            CategoryId = 14L,
                            Description = "Artykuły dla zwierząt",
                            ExpirationDate = new DateTime(2024, 6, 19, 17, 17, 20, 537, DateTimeKind.Utc).AddTicks(7514),
                            Name = "Jakaś tam karma ogólna",
                            Price = 112.2m
                        },
                        new
                        {
                            Id = 15L,
                            CategoryId = 15L,
                            Description = "Utrzymanie czystości",
                            ExpirationDate = new DateTime(2024, 7, 11, 17, 17, 20, 537, DateTimeKind.Utc).AddTicks(7531),
                            Name = "Jakaś tam miotła",
                            Price = 234m
                        },
                        new
                        {
                            Id = 16L,
                            CategoryId = 16L,
                            Description = "Pielęgnacja",
                            ExpirationDate = new DateTime(2024, 6, 29, 17, 17, 20, 537, DateTimeKind.Utc).AddTicks(7534),
                            Name = "Jakiś tam krem",
                            Price = 1412.2m
                        },
                        new
                        {
                            Id = 17L,
                            CategoryId = 17L,
                            Description = "Makijaż",
                            ExpirationDate = new DateTime(2024, 6, 19, 17, 17, 20, 537, DateTimeKind.Utc).AddTicks(7557),
                            Name = "Jakaś tam podkład",
                            Price = 112.2m
                        },
                        new
                        {
                            Id = 18L,
                            CategoryId = 18L,
                            Description = "Perfumy",
                            ExpirationDate = new DateTime(2024, 7, 11, 17, 17, 20, 537, DateTimeKind.Utc).AddTicks(7564),
                            Name = "Jakaś tam dezodorant",
                            Price = 234m
                        },
                        new
                        {
                            Id = 19L,
                            CategoryId = 19L,
                            Description = "Domowa apteczka",
                            ExpirationDate = new DateTime(2024, 6, 29, 17, 17, 20, 537, DateTimeKind.Utc).AddTicks(7567),
                            Name = "Jakiś tam bandarz",
                            Price = 1412.2m
                        },
                        new
                        {
                            Id = 20L,
                            CategoryId = 20L,
                            Description = "Urządzenia medyczne",
                            ExpirationDate = new DateTime(2024, 6, 19, 17, 17, 20, 537, DateTimeKind.Utc).AddTicks(7569),
                            Name = "Jakiś tam rozrusznik serca",
                            Price = 112.2m
                        },
                        new
                        {
                            Id = 21L,
                            CategoryId = 21L,
                            Description = "Medycyna naturalna",
                            ExpirationDate = new DateTime(2024, 7, 11, 17, 17, 20, 537, DateTimeKind.Utc).AddTicks(7571),
                            Name = "Jakaś tam herbatka naturalna",
                            Price = 234m
                        },
                        new
                        {
                            Id = 22L,
                            CategoryId = 22L,
                            Description = "Opony i felgi",
                            ExpirationDate = new DateTime(2024, 10, 27, 17, 17, 20, 537, DateTimeKind.Utc).AddTicks(7574),
                            Name = "Jakieś tam felgi",
                            Price = 1412.2m
                        },
                        new
                        {
                            Id = 23L,
                            CategoryId = 23L,
                            Description = "Części samochodowe",
                            ExpirationDate = new DateTime(2024, 10, 19, 17, 17, 20, 537, DateTimeKind.Utc).AddTicks(7576),
                            Name = "Jakaś tam lampa",
                            Price = 112.2m
                        },
                        new
                        {
                            Id = 24L,
                            CategoryId = 24L,
                            Description = "Warsztat",
                            ExpirationDate = new DateTime(2024, 6, 29, 17, 17, 20, 537, DateTimeKind.Utc).AddTicks(7578),
                            Name = "Jakaś tam śrubka",
                            Price = 234m
                        },
                        new
                        {
                            Id = 25L,
                            CategoryId = 25L,
                            Description = "Smartfony",
                            ExpirationDate = new DateTime(2024, 10, 19, 17, 17, 20, 537, DateTimeKind.Utc).AddTicks(7580),
                            Name = "Jakiś tam IPhone",
                            Price = 112.2m
                        },
                        new
                        {
                            Id = 26L,
                            CategoryId = 26L,
                            Description = "Tablety",
                            ExpirationDate = new DateTime(2024, 6, 29, 17, 17, 20, 537, DateTimeKind.Utc).AddTicks(7583),
                            Name = "Jakiś tam tablet",
                            Price = 234.1m
                        },
                        new
                        {
                            Id = 27L,
                            CategoryId = 27L,
                            Description = "Laptopy",
                            ExpirationDate = new DateTime(2024, 10, 19, 17, 17, 20, 537, DateTimeKind.Utc).AddTicks(7585),
                            Name = "Jakiś tam laptop acer",
                            Price = 112.2m
                        },
                        new
                        {
                            Id = 28L,
                            CategoryId = 28L,
                            Description = "Komputery stacjonarne",
                            ExpirationDate = new DateTime(2024, 6, 29, 17, 17, 20, 537, DateTimeKind.Utc).AddTicks(7604),
                            Name = "Jakiś tam stacjonarny",
                            Price = 234.1m
                        },
                        new
                        {
                            Id = 29L,
                            CategoryId = 29L,
                            Description = "AGD małe",
                            ExpirationDate = new DateTime(2024, 10, 19, 17, 17, 20, 537, DateTimeKind.Utc).AddTicks(7607),
                            Name = "Jakieś tam małe agd",
                            Price = 112.2m
                        },
                        new
                        {
                            Id = 30L,
                            CategoryId = 30L,
                            Description = "AGD do zabudowy",
                            ExpirationDate = new DateTime(2024, 6, 29, 17, 17, 20, 537, DateTimeKind.Utc).AddTicks(7609),
                            Name = "Jakaś tam agd zabudowa",
                            Price = 234.1m
                        },
                        new
                        {
                            Id = 31L,
                            CategoryId = 31L,
                            Description = "AGD",
                            ExpirationDate = new DateTime(2024, 6, 29, 17, 17, 20, 537, DateTimeKind.Utc).AddTicks(7611),
                            Name = "Jakiś tam odkurzacz agd",
                            Price = 234.1m
                        },
                        new
                        {
                            Id = 32L,
                            CategoryId = 32L,
                            Description = "Garnki i patelnie",
                            ExpirationDate = new DateTime(2024, 10, 19, 17, 17, 20, 537, DateTimeKind.Utc).AddTicks(7613),
                            Name = "Jakiś tam garnek",
                            Price = 112.2m
                        },
                        new
                        {
                            Id = 33L,
                            CategoryId = 33L,
                            Description = "Dekoracje i ozdoby",
                            ExpirationDate = new DateTime(2024, 6, 29, 17, 17, 20, 537, DateTimeKind.Utc).AddTicks(7616),
                            Name = "Jakaś tam dekoracja",
                            Price = 234.1m
                        },
                        new
                        {
                            Id = 34L,
                            CategoryId = 34L,
                            Description = "Piły i pilarki",
                            ExpirationDate = new DateTime(2024, 10, 19, 17, 17, 20, 537, DateTimeKind.Utc).AddTicks(7622),
                            Name = "Jakaś tam piła",
                            Price = 112.2m
                        },
                        new
                        {
                            Id = 35L,
                            CategoryId = 35L,
                            Description = "Odkurzacze przemysłowe",
                            ExpirationDate = new DateTime(2024, 6, 29, 17, 17, 20, 537, DateTimeKind.Utc).AddTicks(7624),
                            Name = "Jakiś tam przemysłowy odkurzacz",
                            Price = 234.1m
                        },
                        new
                        {
                            Id = 36L,
                            CategoryId = 36L,
                            Description = "Nawozy i preparaty",
                            ExpirationDate = new DateTime(2024, 10, 19, 17, 17, 20, 537, DateTimeKind.Utc).AddTicks(7627),
                            Name = "Jakiś tam nawóz",
                            Price = 112.2m
                        },
                        new
                        {
                            Id = 37L,
                            CategoryId = 37L,
                            Description = "Meble ogrodowe",
                            ExpirationDate = new DateTime(2024, 6, 29, 17, 17, 20, 537, DateTimeKind.Utc).AddTicks(7629),
                            Name = "Jakiś tam mebel do ogrodu",
                            Price = 234.1m
                        },
                        new
                        {
                            Id = 38L,
                            CategoryId = 38L,
                            Description = "Kawy",
                            ExpirationDate = new DateTime(2024, 10, 19, 17, 17, 20, 537, DateTimeKind.Utc).AddTicks(7648),
                            Name = "Jakaś tam kawa",
                            Price = 112.2m
                        },
                        new
                        {
                            Id = 39L,
                            CategoryId = 39L,
                            Description = "Herbaty",
                            ExpirationDate = new DateTime(2024, 6, 29, 17, 17, 20, 537, DateTimeKind.Utc).AddTicks(7651),
                            Name = "Jakaś tam herbata",
                            Price = 234.1m
                        },
                        new
                        {
                            Id = 40L,
                            CategoryId = 40L,
                            Description = "Karmy",
                            ExpirationDate = new DateTime(2024, 10, 19, 17, 17, 20, 537, DateTimeKind.Utc).AddTicks(7653),
                            Name = "Jakaś tam karma",
                            Price = 112.2m
                        },
                        new
                        {
                            Id = 41L,
                            CategoryId = 41L,
                            Description = "Legowiska",
                            ExpirationDate = new DateTime(2024, 6, 29, 17, 17, 20, 537, DateTimeKind.Utc).AddTicks(7656),
                            Name = "Jakieś tam legowisko",
                            Price = 234.1m
                        },
                        new
                        {
                            Id = 42L,
                            CategoryId = 42L,
                            Description = "Środki czyszczące",
                            ExpirationDate = new DateTime(2024, 10, 19, 17, 17, 20, 537, DateTimeKind.Utc).AddTicks(7658),
                            Name = "Jakaś tam szmatka",
                            Price = 112.2m
                        },
                        new
                        {
                            Id = 43L,
                            CategoryId = 43L,
                            Description = "Suszarki na pranie",
                            ExpirationDate = new DateTime(2024, 6, 29, 17, 17, 20, 537, DateTimeKind.Utc).AddTicks(7660),
                            Name = "Jakaś tam suszarka",
                            Price = 234.1m
                        },
                        new
                        {
                            Id = 44L,
                            CategoryId = 44L,
                            Description = "Kremy do twarzy",
                            ExpirationDate = new DateTime(2024, 10, 19, 17, 17, 20, 537, DateTimeKind.Utc).AddTicks(7662),
                            Name = "Jakiś tam krem na twarz",
                            Price = 112.2m
                        },
                        new
                        {
                            Id = 45L,
                            CategoryId = 45L,
                            Description = "Szampony",
                            ExpirationDate = new DateTime(2024, 6, 29, 17, 17, 20, 537, DateTimeKind.Utc).AddTicks(7667),
                            Name = "Jakiś tam szampon",
                            Price = 234.1m
                        },
                        new
                        {
                            Id = 46L,
                            CategoryId = 46L,
                            Description = "Makijaż ust",
                            ExpirationDate = new DateTime(2024, 10, 19, 17, 17, 20, 537, DateTimeKind.Utc).AddTicks(7669),
                            Name = "Jakaś tam szminka",
                            Price = 112.2m
                        },
                        new
                        {
                            Id = 47L,
                            CategoryId = 47L,
                            Description = "Sztuczne rzęsy",
                            ExpirationDate = new DateTime(2024, 6, 29, 17, 17, 20, 537, DateTimeKind.Utc).AddTicks(7672),
                            Name = "Jakaś tam rzęsa",
                            Price = 234.1m
                        },
                        new
                        {
                            Id = 48L,
                            CategoryId = 48L,
                            Description = "Zestawy",
                            ExpirationDate = new DateTime(2024, 10, 19, 17, 17, 20, 537, DateTimeKind.Utc).AddTicks(7674),
                            Name = "Jakiś tam zestaw perfum",
                            Price = 112.2m
                        },
                        new
                        {
                            Id = 49L,
                            CategoryId = 49L,
                            Description = "Wody toaletowe",
                            ExpirationDate = new DateTime(2024, 6, 29, 17, 17, 20, 537, DateTimeKind.Utc).AddTicks(7692),
                            Name = "Jakaś tam woda",
                            Price = 234.1m
                        },
                        new
                        {
                            Id = 50L,
                            CategoryId = 50L,
                            Description = "Suplementy diety",
                            ExpirationDate = new DateTime(2024, 10, 19, 17, 17, 20, 537, DateTimeKind.Utc).AddTicks(7695),
                            Name = "Jakiś tam suplement",
                            Price = 112.2m
                        },
                        new
                        {
                            Id = 51L,
                            CategoryId = 51L,
                            Description = "Leki bez recepty",
                            ExpirationDate = new DateTime(2024, 6, 29, 17, 17, 20, 537, DateTimeKind.Utc).AddTicks(7697),
                            Name = "Jakaś tam tabletka",
                            Price = 234.1m
                        },
                        new
                        {
                            Id = 52L,
                            CategoryId = 52L,
                            Description = "Inhalatory",
                            ExpirationDate = new DateTime(2024, 10, 19, 17, 17, 20, 537, DateTimeKind.Utc).AddTicks(7700),
                            Name = "Jakiś tam inhalator",
                            Price = 112.2m
                        },
                        new
                        {
                            Id = 53L,
                            CategoryId = 53L,
                            Description = "Termometry",
                            ExpirationDate = new DateTime(2024, 6, 29, 17, 17, 20, 537, DateTimeKind.Utc).AddTicks(7703),
                            Name = "Jakiś tam termometr",
                            Price = 234.1m
                        },
                        new
                        {
                            Id = 54L,
                            CategoryId = 54L,
                            Description = "Produkty konopne",
                            ExpirationDate = new DateTime(2024, 10, 19, 17, 17, 20, 537, DateTimeKind.Utc).AddTicks(7705),
                            Name = "Jakaś tam roślinka CBD",
                            Price = 112.2m
                        },
                        new
                        {
                            Id = 55L,
                            CategoryId = 55L,
                            Description = "Olejki eteryczne",
                            ExpirationDate = new DateTime(2024, 6, 29, 17, 17, 20, 537, DateTimeKind.Utc).AddTicks(7708),
                            Name = "Jakiś tam olejek",
                            Price = 234.1m
                        },
                        new
                        {
                            Id = 56L,
                            CategoryId = 56L,
                            Description = "Felgi aluminiowe",
                            ExpirationDate = new DateTime(2024, 10, 19, 17, 17, 20, 537, DateTimeKind.Utc).AddTicks(7710),
                            Name = "Jakaś tam felga alu",
                            Price = 112.2m
                        },
                        new
                        {
                            Id = 57L,
                            CategoryId = 57L,
                            Description = "Do motocykli",
                            ExpirationDate = new DateTime(2024, 6, 29, 17, 17, 20, 537, DateTimeKind.Utc).AddTicks(7712),
                            Name = "Jakieś tam motory",
                            Price = 234.1m
                        },
                        new
                        {
                            Id = 58L,
                            CategoryId = 58L,
                            Description = "Układ zawieszenia",
                            ExpirationDate = new DateTime(2024, 10, 19, 17, 17, 20, 537, DateTimeKind.Utc).AddTicks(7715),
                            Name = "Jakaś tam sprężyna ",
                            Price = 112.2m
                        },
                        new
                        {
                            Id = 59L,
                            CategoryId = 59L,
                            Description = "Części karoserii",
                            ExpirationDate = new DateTime(2024, 6, 29, 17, 17, 20, 537, DateTimeKind.Utc).AddTicks(7717),
                            Name = "Jakaś tam maska",
                            Price = 234.1m
                        },
                        new
                        {
                            Id = 60L,
                            CategoryId = 60L,
                            Description = "Zestawy narzędzi",
                            ExpirationDate = new DateTime(2024, 10, 19, 17, 17, 20, 537, DateTimeKind.Utc).AddTicks(7720),
                            Name = "Jakaś tam paczka narzędzi",
                            Price = 112.2m
                        },
                        new
                        {
                            Id = 61L,
                            CategoryId = 61L,
                            Description = "Klucze",
                            ExpirationDate = new DateTime(2024, 6, 29, 17, 17, 20, 537, DateTimeKind.Utc).AddTicks(7722),
                            Name = "Jakiś tam klucz",
                            Price = 234.1m
                        },
                        new
                        {
                            Id = 62L,
                            CategoryId = 62L,
                            Description = "Odkurzacze pionowe",
                            ExpirationDate = new DateTime(2024, 10, 19, 17, 17, 20, 537, DateTimeKind.Utc).AddTicks(7724),
                            Name = "Jakiś tam odkurzacz pionowy 2000",
                            Price = 112.2m
                        },
                        new
                        {
                            Id = 63L,
                            CategoryId = 63L,
                            Description = "Do kuchni",
                            ExpirationDate = new DateTime(2024, 6, 29, 17, 17, 20, 537, DateTimeKind.Utc).AddTicks(7727),
                            Name = "Jakiś tam zlew",
                            Price = 234.1m
                        },
                        new
                        {
                            Id = 64L,
                            CategoryId = 64L,
                            Description = "Płyty grzewcze",
                            ExpirationDate = new DateTime(2024, 10, 19, 17, 17, 20, 537, DateTimeKind.Utc).AddTicks(7729),
                            Name = "Jakaś tam grzałka",
                            Price = 112.2m
                        },
                        new
                        {
                            Id = 65L,
                            CategoryId = 65L,
                            Description = "Okapy",
                            ExpirationDate = new DateTime(2024, 6, 29, 17, 17, 20, 537, DateTimeKind.Utc).AddTicks(7731),
                            Name = "Jakiś tam okap",
                            Price = 234.1m
                        },
                        new
                        {
                            Id = 66L,
                            CategoryId = 66L,
                            Description = "Lodówki",
                            ExpirationDate = new DateTime(2024, 10, 19, 17, 17, 20, 537, DateTimeKind.Utc).AddTicks(7738),
                            Name = "Jakaś tam lodówka ",
                            Price = 112.2m
                        },
                        new
                        {
                            Id = 67L,
                            CategoryId = 67L,
                            Description = "Pralki",
                            ExpirationDate = new DateTime(2024, 6, 29, 17, 17, 20, 537, DateTimeKind.Utc).AddTicks(7740),
                            Name = "Jakaś tam pralka",
                            Price = 234.1m
                        });
                });

            modelBuilder.Entity("TreeCraftingVoyager.Server.Models.Management.Account", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("TreeCraftingVoyager.Server.Models.Management.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("TreeCraftingVoyager.Server.Models.Management.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("TreeCraftingVoyager.Server.Models.Management.Account", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("TreeCraftingVoyager.Server.Models.Management.Account", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("TreeCraftingVoyager.Server.Models.Management.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TreeCraftingVoyager.Server.Models.Management.Account", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("TreeCraftingVoyager.Server.Models.Management.Account", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TreeCraftingVoyager.Server.Models.Entities.Category", b =>
                {
                    b.HasOne("TreeCraftingVoyager.Server.Models.Entities.Category", "Parent")
                        .WithMany("Childrens")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("TreeCraftingVoyager.Server.Models.Entities.Product", b =>
                {
                    b.HasOne("TreeCraftingVoyager.Server.Models.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("TreeCraftingVoyager.Server.Models.Entities.Category", b =>
                {
                    b.Navigation("Childrens");
                });
#pragma warning restore 612, 618
        }
    }
}
